excluded:
  - Carthage
  - CarthageAlt
  - .build

disabled_rules:
 - trailing_whitespace
 - function_parameter_count
 - todo
 - line_length

identifier_name:
  excluded:
    - id
    - Log
    - Calculator
    - φ1
    - φ2
    - φ3
    - λ1
    - λ2
    - λ3
    - Δλ
    - Bx
    - By
    - duplicates(indices:)
    - selfIntersects(segmentIndices:)
    - selfIntersects(ringIndices:)
    - ringSimpleViolations(_:)
    - holeOutside(ringIndices:)
    - multipointSimpleViolations(_:)
    - lineStringSimpleViolations(_:)
    - multiLineStringSimpleViolations(_:)
    - polygonSimpleViolations(_:)
    - multiPolygonSimpleViolations(_:)
