excluded:
  - Carthage
  - CarthageAlt

disabled_rules:
 - trailing_whitespace
 - function_parameter_count
 - todo
 - line_length

identifier_name:
  excluded:
    - id
    - Log
    - φ1
    - φ2
    - φ3
    - λ1
    - λ2
    - λ3
    - Δλ
    - Bx
    - By
